# Generated by Django 5.0 on 2023-12-31 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integrantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_integrante', models.CharField(max_length=255)),
                ('Telefone', models.IntegerField()),
            ],
        ),
    ]
