# Generated by Django 5.0 on 2023-12-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_alter_radio_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='Whatsapp',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
