# Generated by Django 5.0 on 2023-12-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_radio_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radio',
            name='Whatsapp',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
