# Generated by Django 5.0 on 2023-12-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_alter_radio_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
